
// WINDOW DEFINE(s)
#define SCREEN_WIDTH 1440.0f
#define SCREEN_HEIGHT 900.0f
#define TITLE_NAME "OK Engine 2D"

// GRAVITY DEFINE(s)
#define GRAVITY_DEFAULT 1.0f
#define GRAVITY_DOWNFORCE 5.0f

// PLAYER DEFINE(s)
#define PLAYER_SPEED_VERTICAL 0.0f
#define PLAYER_SPEED_HORIZONTAL 300.0f
#define PLAYER_SPEED 300.0f
#define PLAYER_JUMP_SPEED 20.0f

// ENEMY DEFINE(s)
#define ENEMY_SPEED_VERTICAL 0.0f
#define ENEMY_SPEED_HORIZONTAL 300.0f
#define ENEMY_JUMP_SPEED 10.0f